FROM golang:1.22.2-alpine3.24 AS builder

WORKDIR /src
COPY burn-emulator-api/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/burn-emulator-api ./cmd/server

FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app
COPY --from=builder /out/burn-emulator-api /app/burn-emulator-api
COPY --from=builder /src/config /app/config

EXPOSE 8080
ENTRYPOINT ["/app/burn-emulator-api"]
