dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        treatment_area: data/training_data/${varloc}/sample_pa.geojson
        fuels_paths:
            baseline: data/training_data/fuels_${inputs_version}/baseline
            treatment: data/training_data/fuels_${inputs_version}/legalmax
        burn_paths: null
        wind_ang_paths: null
        wind_range: ${wind_range}
        topo_path: data/training_data/topo_${inputs_version}

        # default configs for PA smoke test
        fbfm_map_path: configs/fbfm_behavior_adjectives.csv
        treatment_buff: 960
        ignition_density: 20
        ignition_method: uniform
        treatment_seed: 42
        wind_seed: 42
        window_size: 129

dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        batch_size: 32
        shuffle: false
        pin_memory: true
        drop_last: false

activation:
    class_path: torch.nn.Sigmoid

varloc: ${varloc}
