dataset:
    class_path: burn_emulator.datasets.IgnitionDataset
    init_args:
        ignitions_path: /mnt/data/dschmidt/cbp_approx_poc/training_data_10Aug2026/ignition_locations.csv
        fuels_paths:
            -  /mnt/data/dschmidt/cbp_approx_poc/legalmax_baseline_FF_05Aug2026/
            -  /mnt/data/dschmidt/cbp_approx_poc/legalmax_legalmax_FF_05Aug2026/
        burn_paths:
            -  /mnt/data/dschmidt/cbp_approx_poc/training_data_10Aug2026/baseline
            -  /mnt/data/dschmidt/cbp_approx_poc/training_data_10Aug2026/legalmax
        wind_ang_paths:
            -  /mnt/data/dschmidt/cbp_approx_poc/training_data_10Aug2026/baseline/outputs_table.csv
            -  /mnt/data/dschmidt/cbp_approx_poc/training_data_10Aug2026/legalmax/outputs_table.csv
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        window_size: 129
        jitter: null