model_name: wc711_480_single_df64
model:
    class_path: burn_emulator.models.circlenet.CircleNet
    init_args:
        n_channels: 19
        n_outputs: 4
        image_size: 129
        bilinear: true

activation:
    class_path: torch.nn.Sigmoid

dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        treatment_area: configs/wc711/pa1_area.geojson
        treatment_buff: 960
        ignition_density: 5e-05
        ignition_method: uniform
        treatment_seed: 42
        fuels_paths:
            baseline: data/legalmax_baseline_FF_05Aug2026
            treatment: data/legalmax_legalmax_FF_05Aug2026
        burn_paths: null
        wind_ang_paths: null
        wind_range: [225, 269]
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        window_size: 129
        jitter: null
        num_classes: 4
        
dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        batch_size: 4
        shuffle: false
        pin_memory: false
        drop_last: false
