dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        ignitions_path: data/training_data_14Aug2026/ignition_locations.csv
        burn_paths: null
        topo_path: data/topo
        window_size: 129
activation:
    class_path: torch.nn.Sigmoid
test_name: legalmax
max_write_workers: 4
out_channels: 4