dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        ignitions_path: data/training_data_14Aug2026/ignition_locations.csv
        fuels_paths:
            baseline:  data/legalmax_baseline_FF_05Aug2026
        burn_paths: null
        topo_path: data/topo
        window_size: 129
        jitter: null
activation:
    class_path: torch.nn.Sigmoid
test_name: baseline
max_write_workers: 4
out_channels: 4