dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        ignitions_path: data/training_data_14Aug2026/ignition_locations.csv
        burn_paths: null
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        window_size: 129
        jitter: null
activation:
    class_path: burn_emulator.criterions.DesmoothedActivation
    init_args:
        activation:
            class_path: torch.nn.Sigmoid
        label_smoothing: .125
        multiclass: false
test_name: legalmax
max_write_workers: 4
out_channels: 4