dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        ignitions_path: data/training_data_14Aug2026/ignition_locations.csv
        fuels_paths:
            baseline:   data/legalmax_baseline_FF_05Aug2026/
            treatment:  data/legalmax_legalmax_FF_05Aug2026/
        burn_paths:
            baseline:   data/training_data_14Aug2026/baseline
            treatment:  data/training_data_14Aug2026/legalmax
        wind_ang_paths:
            baseline:   data/training_data_14Aug2026/baseline/outputs_table.csv
            treatment:  data/training_data_14Aug2026/legalmax/outputs_table.csv
        topo_path: data/topo
        burn_times: [480]
        window_size: 129
        jitter: null
        num_classes: 4
dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        batch_size: 32
        shuffle: true
        pin_memory: false
        drop_last: true
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: .0003
criterion:
    class_path: burn_emulator.criterions.DiceFocalLoss
    init_args:
        multiclass: false
        dice_weight: .5
        focal_weight: .5
        label_smoothing: .125
num_epochs: 64
model_name: wc711