dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/4_baseline/4_ignitions_locations.csv
        wind_ang_paths:
            -  data/outputs_12Aug2026/4_baseline/4_outputs_table.csv

test_name: 4_baseline
