dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/5_baseline/5_ignitions_locations.csv
        wind_ang_paths:
            -  data/outputs_12Aug2026/5_baseline/5_outputs_table.csv

test_name: 5_baseline
