dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/6_baseline/6_ignitions_locations.csv
        wind_ang_paths:
            -  data/outputs_12Aug2026/6_baseline/6_outputs_table.csv

test_name: 6_baseline
