dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/8_baseline/8_ignitions_locations.csv
        wind_ang_paths:
            -  data/outputs_12Aug2026/8_baseline/8_outputs_table.csv

test_name: 8_baseline
