dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/2_legalmax/2_ignitions_locations.csv
        fuels_paths:
            baseline:  data/outputs_12Aug2026_re/2_legalmax
        wind_ang_paths:
            baseline:  data/outputs_12Aug2026/2_baseline/2_outputs_table.csv

test_name: 2_legalmax
