dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/7_legalmax/7_ignitions_locations.csv
        fuels_paths:
            -  data/outputs_12Aug2026_re/7_legalmax
        wind_ang_paths:
            -  data/outputs_12Aug2026/7_baseline/7_outputs_table.csv

test_name: 7_legalmax
