dataset:
    init_args:
        ignitions_path: data/outputs_12Aug2026/9_legalmax/9_ignitions_locations.csv
        fuels_paths:
            -  data/outputs_12Aug2026_re/9_legalmax
        wind_ang_paths:
            -  data/outputs_12Aug2026/9_baseline/9_outputs_table.csv

test_name: 9_legalmax
