architecture: circlepp
data_version: 28Aug2026 # this is the training data version which gets parsed later

activation:
    class_path: torch.nn.Sigmoid

dataset:
    class_path: burn_emulator.datasets.varloc.VarLoc
    init_args:
        fbfm_map_path: configs/fbfm_behavior_adjectives.csv
        treatment_buff: 960
        ignition_density: 20
        ignition_method: uniform
        treatment_seed: 42
        wind_range: ${wind_range}
        wind_seed: 42
        window_size: 129

dataloader:
    class_path: torch.utils.data.DataLoader
    init_args:
        batch_size: 4
        shuffle: false
        pin_memory: false
        drop_last: false
